### ISSUE TITLE
Nextcloud Talk iOS Still not connecting on non-standard https port

### ISSUE THREAD

**Issue by Nextcloud-User** [nextcloud/talk-ios#120]
According to issue #93, this issue was resolved but it certainly was not.  I have checked with every new release in the past few months and problem persists.

Nextcloud App connects just fine but the Talk app is simply not able to handle a port entry in the URL:

Example:  https://sitename.com:8080/nextcloud

It connects ok if on an internal lan as a port is not entered into the url.

https://github.com/nextcloud/talk-android/issues/93

**Comment by Ivansss** [comment]
Hi @Nextcloud-User 
Nextcloud Talk iOS requires an HTTPS connection with your NC server.
I'm gonna add it in the README.

**Comment by Nextcloud-User** [comment]
With all due respect, it's insulting that tickets like this are closed with comments like that.

It was clearly spelled out that an HTTPS connection was being used. 

The problem with this app is that, unlike the nextcloud file app on the same OS, it doesn't properly parse non-standard port entries in the URL.

It is my hope that an admin or moderator reopen this ticket and finally addresses the issue with the devs.

Thank you.

**Comment by Ivansss** [comment]
Sorry @Nextcloud-User , my mistake.

I read https://github.com/nextcloud/talk-android/issues/93 and thought that you were using a HTTP connection.
Since this was a problem for some other users, I decided to finally update requirements in README pointing that a HTTPS connection is mandatory to use this app.

This app follows Apple ATS (App Transport Security). If you can't connect to you server, we should investigate why ATS doesn't like your server SSL setup.
Nextcloud iOS app (Files app), uses an ATS exception, and that's probably the reason you are able to connect with your server with the Files app. Apple announced that they were not going to allow apps with this exception in the App Store at some point, and that's the reason this exeption is not included in the Nextcloud Talk iOS app.

Could you send me an email to `ivan AT nextcloud DOT com` with a test account of your Nextcloud server? I could debug what could be wrong there then :)

**Comment by darkneo29** [comment]
I am having same issue. Using port 444 and the iOS app won’t connect. Please let me know how I can help troubleshoot this issue.

**Comment by darkneo29** [comment]
FYI works via web browser no issues.  Nextcloud standard file app works as well. Just not the talk app.

**Comment by darkneo29** [comment]
All fixed.  I signed my certificate and went back to 443 port and its
working fine


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by darkneo29** [comment]
Working on all ports after valid certificate as well.  Believe this case can be closed
