### ISSUE TITLE
Unread messages badge app icon

### ISSUE THREAD

**Issue by andrew-paglinawan** [nextcloud/talk-ios#125]
Since we don't get notifications on every message except for mentions and calls, I think we should at least have a notification badge app icon that shows the number of unread messages. Currently, you need to open the app to check if you have unread messages.

**Comment by Ivansss** [comment]
The problem here is when the app is in the background or killed by the user.
We can't keep a connection with the server in these situations, so the only way to warn the app about new messages is via push notifications.
We are working on notifying users on every new message. https://github.com/nextcloud/spreed/issues/875

**Comment by andrew-paglinawan** [comment]
Thanks Ivan, notification on every message is gonna be awesome. Right now it’s hard to keep friends and family use NC talk without this feature. Looking forward to the next update.
