### ISSUE TITLE
Issue with push notification

### ISSUE THREAD

**Issue by Vuong-Dao** [nextcloud/talk-ios#250]
Hi Team. 
I got a problem with push notification. According to your demo app, I will receive a push notification when I received a message. I already tried with your app in iTunes Connect with my server. It worked perfectly. But I tried to clone your source code and run it with my bundle id. The notification doesn't work.

I also got the success to subscribe to the token
2019-07-30 09:12:50.136560+0700 VideoCalls[311:12179] Subscribed to NC server successfully.
2019-07-30 09:12:52.047768+0700 VideoCalls[311:12179] Subscribed to Push Notification server successfully.

Do we need to set up something on our developer account?
Thanks

**Comment by nickvergessen** [comment]
It's not a demo app, but you actually have to use our app for now.

The only other way to get notifications working would be if you run your own "push notification proxy", but that is not publicly available without a subscription of Nextcloud, because otherwise anyone could put a fork of our App into the appstores.

@Ivansss Should we maybe change the Push Proxy to return a failure when trying to subscribe with a different bundle id? But actually we don't know it yet, right?

**Comment by Vuong-Dao** [comment]
> but that is not publicly available without a subscription of Nextcloud

How we can subscribe to it? Do you have any docs to guide us to create our own "push notification proxy"?

BTW: Thank you for a quick response

**Comment by nickvergessen** [comment]
Well you need an enterprise subscription with branding support:
https://nextcloud.com/enterprise/

**Comment by Vuong-Dao** [comment]
Yup. Thanks
