### ISSUE TITLE
iOS Talk app seems to ignore HTTP

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/talk-ios#252]
I understand, that the use of microphone and webcam underlies the need of HTTPS (according to the notification @ webview). But why the app simply throws the message "Nextcloud server not found".

May it could write down that only https is supported, better would it be to work with both protocols (HTTP and HTTPS). 

btw. the request to write the protocol "https://..." is uneeded if it will internal cut off and never used. to simplify for users it could be shorted (easier to write, understand etc. for "just"-users)

Android version i couldn't test, but other responses and tests @forum seem to show, that it runs there. (they descibe that the ios app throws the message not found, the android app works flawless with the server)

**Comment by SystemKeeper** [comment]
Just tested the latest version with http:// instead of https:// and it’s working fine.

**Comment by SystemKeeper** [comment]
To add some additional information here:
Apple requires apps to be ATS compliant, so essential you are required to use HTTPS instead of HTTP. This is also true for Nextcloud Talk on iOS (as noted in [Prerequisites](https://github.com/nextcloud/talk-ios#prerequisites)).
ATS however does not apply to some special cases (see [apples documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW54)), for example:
- Internet protocol (IP) addresses
- Unqualified host names

So it is possible to connect to `http://192.168.1.1`, but it is not possible to connect to `http://nextcloud.mydomain.com`

There are no plans to change the ATS requirement.

> btw. the request to write the protocol "https://..." is uneeded if it will internal cut off and never used. to simplify for users it could be shorted (easier to write, understand etc. for "just"-users)

Indeed it looks like this is needed, but it will be added automatically if you don't enter it, see here:

https://github.com/nextcloud/talk-ios/blob/3595e0975fba7c2d2d97bfcb980747bcfd1fcdd5/NextcloudTalk/LoginViewController.m#L108-L110
