### ISSUE TITLE
iOS 13.3 - Bottom nav bar not displaying.

### ISSUE THREAD

**Issue by nextra06** [nextcloud/talk-ios#271]
Expected behaviour
Talk app for iOS should display bottom nav bar to let users access settings page.

Actual behaviour
Bottom nav bar not displayed / hidden.

App version
7.1.1

Server configuration
Operating system:
Raspbian Buster (Raspberry Pi 4B 4GB)
Web server:
Apache 2
Database:
MySQL (Socket)
PHP version:
7.3.11
Nextcloud version: (see Nextcloud admin page)
16.0.5

**Comment by Ivansss** [comment]
Hi @nextra06,
The bottom navigation bar was removed in version [3.2.0](https://github.com/nextcloud/talk-ios/releases/tag/v3.2.0).
Since then you can access app settings from the top-left button :)

![settings](https://user-images.githubusercontent.com/4638605/71984921-0f019a80-322a-11ea-8494-eceeef826597.png)
