### ISSUE TITLE
Parts in Dark Mode, no Push and crash.

### ISSUE THREAD

**Issue by andreabasso39** [nextcloud/talk-ios#292]
Hi,
I’ve build app but there is 3 problem:
1- on my iPhone XS Max there is parts in dark mode and other in light mode.

2- no push notification

3- app crash when open new conversation, start call or other. In debug I’ve a simple libd.

Can you help me?

**Comment by Ivansss** [comment]
Hi @balabitalia 

The code is not ready to be built with XCode 11 (and iOS 13 SDK) yet.
You can download XCode 10.3 from https://developer.apple.com/ and use it for building the project.

**Comment by andreabasso39** [comment]
Really thank you for your support @Ivansss I try to build today!

**Comment by andreabasso39** [comment]
ok, I try with Xcode and dark mode issue is solved, but crash when I create a conversation, call not work and push notification not work, if I close app o leave in background and call nothing, I need to open app for see the call or message. Can you help me @Ivansss? If I use official app "nextcloud talk" all work fine.

**Comment by Ivansss** [comment]
Try checking out v8.1.0 tag (That's the latest stable release).
Master branch could be broken sometimes 😅 

Regarding push notifications, only the official app will receive them.
Since the app should be signed with our developer certificate in order to receive messages from the push notification proxy.

**Comment by Ivansss** [comment]
The app can be built with XCode 12 since v10.0
