### ISSUE TITLE
loading room messages takes 20 - 30 secons

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-ios#334]
1. Send a test message to an iOS user
2. Tip on the notification
3. The room opens without the new message
4. After 20 - 30 secons the new message will show up

On Android (same server) it takes 2 - 3 secons to load all the room messages

**Comment by Ivansss** [comment]
Hi @jakobroehrl 
Does this happen when the app was completely killed? Or also when the app is running in the background or foreground?
20 to 30 seconds is quite some time and I have never experienced such long delays (maybe with really bad network conditions)
When the app is completely killed it could take a bit longer since it fetches some info from the server when the app is launch, but it should never take that long with normal network conditions.

**Comment by jakobroehrl** [comment]
No, the app is always running in the background or foreground. 
And it occures on 3 of my about 10 iOS users.

**Comment by jakobroehrl** [comment]
Tested a lot with different iPhones. 
The problem was solved by reinstalling the app! 👍

**Comment by Ivansss** [comment]
Interesting...maybe those iPhones didn't have the latest app version (v9.0+) which caches chat history.
But even with older app versions (without caching), 20-30 seconds is too much time.
Anyways, I'm glad that the problem you were experiencing is gone 😉
