### ISSUE TITLE
How to initiate screensharing from iOS?

### ISSUE THREAD

**Issue by luckman212** [nextcloud/talk-ios#340]
I just learned about the Nextcloud Talk project and it looks wonderful! 

I set up a test instance and got my HTTPS / LetsEncrypt set up and working.

Now I'm trying to figure out if screensharing is possible from an iPhone. My usecase is to allow people to join my nextcloud instance and share their iPhone screen for some remote support. Is that possible? I saw #89 and #190 but still couldn't figure out how to do it.

**Comment by Ivansss** [comment]
Hi @luckman212 :)

Screensharing feature was added in [version 3.4.0](https://github.com/nextcloud/talk-ios/releases/tag/v3.4.0).
The screensharing feature introduced in that version is just "Screensharing as a viewer".
So if someone is sharing a screen using the web app, you will be able to see it with the iOS app.
We want to implement the complete screensharing functionality (the ability to share your iPhone screen) in one of the next versions.

I will leave this issue open to post updates about that feature ;)

**Comment by luckman212** [comment]
@Ivansss Thanks for that info. I'll keep an eye out for the future.

**Comment by Blackclaws** [comment]
I'd also be interested in thsi feature. This is one of the things that still forces me to use Teams occasionally. Any way we can help with this?

**Comment by Ivansss** [comment]
We are going to implement this feature at some point, but there are some other features that we are working on at the moment.

> Any way we can help with this?

Contributions are always welcome :)

**Comment by LukaPitamic** [comment]
@Ivansss I see more and more (of us coaches/leaders) use iPad drawing capabilities for teaching. At the moment we are all forced to use other services (like Skype) which provide screen sharing on iPad to be able to pull this off. It is really a new-age feature since it is the way to reproduce school-line white/black board. Allowing notes, diagrams being created during the explanation of more and more complex concepts need to be translated. Really looking forward you implement this feature.

**Comment by idominiki** [comment]
Would be great if we get this feature as one of the first SPS Customers in Germany! Would be a huge improvement to move from MS Teams to Nextcloud Talk. But we need this feature in the near future.

**Comment by angfer-kn** [comment]
Hello, @nickvergessen 

Alphaview, Zoom and other have this functionality for iOS. If we do not get this feature in Q3 2022, probably we have to move. Screen sharing in iOS is important for schools, because these use often iPads, but not everybody have the possibility for the workaround with Mac or PC. So my question: when will be this functionality?

Thank you.

**Comment by nickvergessen** [comment]
The easiest way to get this on track is by bavking it up with a subscription. Feel free to contact our team for it:
https://nextcloud.com/contact/
Otherwise it will come once it reached the top of the backlog queue and after requests of customers.

**Comment by GVLLIFESTYLE** [comment]
So is there already a way to do screensharing with ipad?
I do have the HPB and nextcloud talk with signaling (self hosted).
My usecase is to share the screen during a online meeting to do some training to my customers.

**Comment by SystemKeeper** [comment]
No, sorry, that functionality is currently not implemented in talk-ios

**Comment by GVLLIFESTYLE** [comment]
If possible please reopen.
This feature is very needed for us as well.
In other solutions, like goto webinar, goto meeting, teams,... it is working out of the box.

**Comment by SystemKeeper** [comment]
This one is still open 😉 only yours is closed as a duplicate to this one.
If you’re a customer feel free to reach out to your account manager for this feature request.

**Comment by GVLLIFESTYLE** [comment]
OK, perfect

**Comment by GVLLIFESTYLE** [comment]
any updates for the roadmap of that feature?

**Comment by SystemKeeper** [comment]
Fixed with https://github.com/nextcloud/talk-ios/pull/1370
