### ISSUE TITLE
No notifications about messages and incoming calls

### ISSUE THREAD

**Issue by AleksovAnry** [nextcloud/talk-ios#344]
Hello! No notifications about messages and incoming calls from iOS app. If I delete app, or exit from account and login again (not always help), it works fine few hours or days, then stops working again.
I use my own TURN & STUN servers, but test it with standard servers and without it.
Any idea/solution?

iOS version13.5.1 (tested on many different phones & iOS versions)
iOS app version 9.0.1
server-sde version 8.0.10
Nextcloud version 18.0.7 (tested on 2 different servers 18.0.7)

**Comment by Ivansss** [comment]
Hi @AleksovAnry 
Could be that you have another session of the same user opened in another device?
If that is the case, you won't receive chat notifications in some scenarios.

This is the scenario where you won't receive chat messages notifications:
User A using iOS app.
User A using web app joins converation A.
User B writes a message in conversation A.
User A won't receive a push notification about the message written by User B on the iOS device, since User A is in conversation A using the web app.

**Comment by Ivansss** [comment]
Closing due to lack of feedback. Feel free to re-open it if you still experience this issue.
