### ISSUE TITLE
Save unsend messages 

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#361]
1. Enter a room
2. Start typing
3. Leave room without sending the message 
4. Re-Enter same room

Expected: The message typed in 2. is still there, ready to send.
Current: The message typed in 2. just vanished. 

v9 added offline support, would be great if that could be extended to save messages which were not yet send yet.

**Comment by Ivansss** [comment]
Thanks for opening this issue!
I think this is a nice feature to add ;)
I will leave this ticket open to post updates.
Don't know if you are an iOS developer @SystemKeeper, but this could be a "good first issue" for someone who wants to contribute :)

**Comment by SystemKeeper** [comment]
I’ve not done any iOS development recently, but always wanted to start iOS development again. So maybe this would indeed be a good first issue. Any chance you could give me a pointer where to start with this feature? 🙃

**Comment by Ivansss** [comment]
Sure 🙂

Since we store NCRoom objects in the database, I would add a new property to that object (e.g. pendingMessage)
https://github.com/nextcloud/talk-ios/blob/master/VideoCalls/NCRoom.h#L73

Then every time a the user is about to leave a chat, I would store the text (if there is any) from the input field in this new room property.
https://github.com/nextcloud/talk-ios/blob/master/VideoCalls/NCChatViewController.m#L274

Every time a user enters a chat, if there is something in that property, we should set that text in the input field.
https://github.com/nextcloud/talk-ios/blob/master/VideoCalls/NCChatViewController.m#L125

Also, we should clean that property every time the user sends a message:
https://github.com/nextcloud/talk-ios/blob/master/VideoCalls/NCChatViewController.m#L637

And I think that should do the job :)
Let me know if you have any other questions and I could help you.

**Comment by SystemKeeper** [comment]
So, finally tried to implement this 😄 

A few remarks:
* I'm always saving the pending text of the input field. Otherwise there would be no way to "delete" a stored pending message by clearing the input field.
* I don't know why `dispatch_async` is needed... Without the dispatch it inserts the text just fine, but in case of multline messages won't change the height of the input field. Any idea or is the dispatch fine?

Let me know what you think!

**Comment by Ivansss** [comment]
> I'm always saving the pending text of the input field. Otherwise there would be no way to "delete" a stored pending message by clearing the input field.

That makes total sense :)
> I don't know why dispatch_async is needed... Without the dispatch it inserts the text just fine, but in case of multline messages won't change the height of the input field. Any idea or is the dispatch fine?

The dispatch_async is fine there.

Once again, thank you for your PR! Very nice and clean code :)

**Comment by Ivansss** [comment]
Btw we have a Nextcloud Talk instance where we invite Nextcloud contributors to be able to communicate more quickly, and we also have channels for e.g. "Talk team" and "Mobile apps".

If you like, I could just give you a guest account via the email address in your commits?

**Comment by SystemKeeper** [comment]
> If you like, I could just give you a guest account via the email address in your commits?

Cool, thanks! Looking forward to it @Ivansss

**Comment by Ivansss** [comment]
> Cool, thanks! Looking forward to it @Ivansss 

You have been already added :) Did you receive an e-mail?
