### ISSUE TITLE
Phone rings on incoming group call

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/talk-ios#384]
Until not long ago, only incoming 1-on-1-calls lead to a ringing phone, while starting group calls only sent a push notification.
This behaviour now changed. Also starting group calls let the iPhone ring.
Has there been a change of strategy or is this an accident?

Tested on 
- iOS 14.0.1
- iPhone 8
- NC server: 20.0.0.9
- Talk server app: unsure
- Talk iOS app: 10.0.1
- Talk high performance back end in operation: yes

**Comment by Ivansss** [comment]
Hi @wiswedel :)

Thanks for bringing this up.

This is not an accident but the result of the VoIP push notification changes that Apple introduced on iOS 13.
The push proxy does not differenciate between one2one calls or group calls, so every call notification is send via VoIP push.
Since iOS 13 VoIP pushes can only be used to notify about calls. So every time an app receives a VoIP push, it needs to present a CallKit incoming call screen.
This is why at the moment all call notifications present an incoming call screen.

We are planning to have an option for this in the conversation based settings once we can implement it in all clients at the same time.

**Comment by wiswedel** [comment]
Thanks for this explaination, @Ivansss.
Shall we keep this issue open in the meantime for others with the same observation?

**Comment by Ivansss** [comment]
We can leave it open and we can close it once the setting per conversation is in place ;)

**Comment by SystemKeeper** [comment]
Fixed by #646
