### ISSUE TITLE
Localization missing in xcode project

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/talk-ios#397]
Transiflex correctly pull translations and adds them to the project, but they are not referenced in the xcode project:

![image](https://user-images.githubusercontent.com/1580193/97970134-5b255900-1dc1-11eb-85e1-9a726ef43a35.png)

(I manually added German here and it works). Downloading from the appstore to a german device also shows the interface in english.

**Comment by Ivansss** [comment]
Hi @SystemKeeper :)
Localization was added after v10.0.1. That's why the version in the App Store is English only.
The next release will include support for some languages (probably the ones that have 100% of translated strings in transifex)
I'm just waiting to have more languages 100% in transifex and then I will add them to the project.

**Comment by SystemKeeper** [comment]
Ah! Sorry, that makes sense :)

**Comment by p-bo** [comment]
Hi @Ivansss
may I ask you to add into xproject also Czech language please? I was surprised to see it missing in installed app (v11.1.3), because translation is maintained at 100% on Transifex (I'm long time translator of whole Nextcloud suite and companion apps into this language, thus familiar with its status).
Many thanks :-)

**Comment by Ivansss** [comment]
Hi @p-bo :)
There was a problem with the mapping of the Czech language. https://github.com/nextcloud/talk-ios/commit/5780b67e1870c31465e0aa85a68f1c30a2797a3d
It will be included in the next release 12.0.1.
Thanks for reporting it ;)

**Comment by p-bo** [comment]
Hi @Ivansss
Thanks for solving it, have a nice day :-)
