### ISSUE TITLE
Keep screen always on when on a call

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/talk-ios#563]
Currently if you're on a call when hover over the camera sensor the screen will go black and sometimes it takes about 10 to 15 seconds to turn back on. I'm currently using IOS 14.6.  It would be nice to have the screen always on while on a call even when someones hovers over the front camera sensor it keep the screen on. I know  that how it works with FaceTime the screen will not turn off even if you place your finger by the front camera sensor. Let me know what you think about this.

**Comment by Ivansss** [comment]
Hi @andyxheli :)
We can't experience that long delays for the sceen to turn back on. For us it just takes ~1 sec.
Does this happen recently or did you always experience that delay?

**Comment by Ivansss** [comment]
Turning the screen off when the proximity sensor is activated prevent undesired button taps.

For example when your put your device close to your ear, the proximity sensor is activated.
This turns the screen off, stop sending video (if in a video call) and change the audio output to the ear speaker.

This is the expected behaviour in most apps so we will leave it like this :)

**Comment by AndyXheli** [comment]
Okay, Thank you for looking into it :)  & sorry to bother.

**Comment by Ivansss** [comment]
No worries 😉
