### ISSUE TITLE
Voice messages are very low volume

### ISSUE THREAD

**Issue by e-caste** [nextcloud/talk-ios#591]
## Steps to reproduce
1. Send a voice message
2. Listen to it on receiving end. Volume is very low

### Expected behaviour
We should be able to listen to voice messages without setting the volume to the max.
It would also be nice to be able to listen to voice messages through the phone speaker privately when the phone is raised to the ear, like other messaging apps do.

### Actual behaviour
A voice message is almost inaudible unless the phone's media volume is set to the max.

## Device information

**Device:** tested on iPhone 7 and iPhone SE 1

**iOS version:** Both 14.6

**Talk version:** 12.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 22.0.0

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 12.0.0

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) no

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) no

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
I've noticed this as well. I was under the impression, that the playback was indeed through earpiece instead of the speaker (it sounded ok for me, if I raised the phone to my ear. @e-caste ?). But in this case the screen was not disabled, resulting in undesired touch inputs...

So I guess two options then:

1. If screen is not covered (through proximity sensor) play through speaker
2. If screen is covered, play through earpiece

Like this? If speaker output is not disired, we should at least make sure to have the screen disabled on proximity.

**Comment by e-caste** [comment]
@SystemKeeper Yes, those should be the two valid options.

By the way, I can also hear through the earpiece, but only because on my phone it doubles as the second phone speaker. In fact, I can also hear through the "music" speaker at the same time.  
On the SE 1 I can only hear through the bottom "music" speaker because on that phone the earpiece does not double as a second speaker.

**Comment by SystemKeeper** [comment]
Ah ok, on my phone it doubles as speaker as well, so in this case volume looks to be too low.

**Comment by Ivansss** [comment]
This issue has been fixed and it will be included in the next release 12.1.0.
Thanks for the report :)
